{:config {:order 0, :description "Tutorial Recording", :name :tutorial}
 :data
 [
  [:node-create [] :map]
  [:node-create [:main] :map]
  [:node-create [:main :my-counter] :map]
  [:value [:main :my-counter] nil 1]
  [:transform-enable [:main :my-counter] :inc [{:io.pedestal.app.messages/topic [:my-counter]}]]
  [:node-create [:main :total-count] :map]
  [:value [:main :total-count] nil 8]
  [:node-create [:main :average-count] :map]
  [:value [:main :average-count] nil 2.67]
  [:node-create [:main :max-count] :map]
  [:value [:main :max-count] nil 5]
  [:node-create [:main :other-counters] :map]
  [:node-create [:main :other-counters "abc"] :map]
  [:value [:main :other-counters "abc"] nil 5]
  [:node-create [:main :other-counters "xyz"] :map]
  [:value [:main :other-counters "xyz"] nil 2]
  [:node-create [:pedestal] :map]
  [:node-create [:pedestal :debug] :map]
  [:node-create [:pedestal :debug :dataflow-time-max] :map]
  [:value [:pedestal :debug :dataflow-time-max] nil 25]
  [:node-create [:pedestal :debug :dataflow-time] :map]
  [:value [:pedestal :debug :dataflow-time] nil 12]
  [:node-create [:pedestal :debug :dataflow-time-avg] :map]
  [:value [:pedestal :debug :dataflow-time-avg] nil 14]
  :break
  [:value [:main :other-counters "xyz"] 2 3]
  [:value [:main :total-count] 8 9]
  [:value [:main :average-count] 2.67 3]
  [:value [:pedestal :debug :dataflow-time] 12 8]
  [:value [:pedestal :debug :dataflow-time-avg] 14 13]
  :break
  [:value [:main :other-counters "abc"] 5 6]
  [:value [:main :total-count] 9 10]
  [:value [:main :average-count] 3 3.33]
  [:value [:main :max-count] 5 6]
  [:value [:pedestal :debug :dataflow-time] 8 10]
  :break
  [:value [:main :other-counters "abc"] 6 7]
  [:value [:main :total-count] 10 11]
  [:value [:main :average-count] 3.33 3.67]
  [:value [:main :max-count] 6 7]
  [:value [:pedestal :debug :dataflow-time] 10 9]
  [:value [:pedestal :debug :dataflow-time-avg] 13 12]
  :break
  [:value [:main :other-counters "abc"] 7 8]
  [:value [:main :total-count] 11 12]
  [:value [:main :average-count] 3.67 4]
  [:value [:main :max-count] 7 8]
  :break
  [:value [:main :total-count] 12 13]
  [:value [:main :average-count] 4 4.33]
  [:value [:main :my-counter] 1 2]
  [:value [:pedestal :debug :dataflow-time] 9 10]
  :break
  [:value [:main :other-counters "xyz"] 3 4]
  [:value [:main :total-count] 13 14]
  [:value [:main :average-count] 4.33 4.67]
  [:value [:pedestal :debug :dataflow-time] 10 8]
  :break
  [:value [:main :other-counters "abc"] 8 9]
  [:value [:main :total-count] 14 15]
  [:value [:main :average-count] 4.67 5]
  [:value [:main :max-count] 8 9]
  [:value [:pedestal :debug :dataflow-time] 8 10]
  [:value [:pedestal :debug :dataflow-time-avg] 12 11]
  :break
  [:value [:main :total-count] 15 16]
  [:value [:main :average-count] 5 5.33]
  [:value [:main :my-counter] 2 3]
  [:value [:pedestal :debug :dataflow-time] 10 9]
  :break
  [:value [:main :total-count] 16 17]
  [:value [:main :average-count] 5.33 5.67]
  [:value [:main :my-counter] 3 4]
  :break
  [:value [:main :other-counters "abc"] 9 10]
  [:value [:main :total-count] 17 18]
  [:value [:main :average-count] 5.67 6]
  [:value [:main :max-count] 9 10]
  [:value [:pedestal :debug :dataflow-time] 9 10]
  :break
  [:value [:main :total-count] 18 19]
  [:value [:main :average-count] 6 6.33]
  [:value [:main :my-counter] 4 5]
  [:value [:pedestal :debug :dataflow-time] 10 9]
  :break
  [:value [:main :other-counters "xyz"] 4 5]
  [:value [:main :total-count] 19 20]
  [:value [:main :average-count] 6.33 6.67]
  [:value [:pedestal :debug :dataflow-time] 9 8]
  :break
  [:value [:main :other-counters "abc"] 10 11]
  [:value [:main :total-count] 20 21]
  [:value [:main :average-count] 6.67 7]
  [:value [:main :max-count] 10 11]
  [:value [:pedestal :debug :dataflow-time] 8 9]
 ]}